# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
librosa==0.10.1
numpy==1.24.3
python==3.8.18
pyyaml==6.0
scikit-learn==1.3.1
scipy==1.10.1
torch==2.1.0
yaml==0.2.5